name: Test
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: [opened, synchronize]
  schedule:
      - cron:  '*/5 14 * * *'

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo 'Hello World!!'
