name: Test
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: [opened, synchronize]
  schedule:
      - cron:  '*/10 */3 * * *'

jobs:
  build:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo 'Hello World!!'

      - run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
