name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '*/10 */4 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 day'
        # Optional inputs
        # skip-tags: true
        skip-recent: 5
